#!/usr/bin/env python3
"""Generate PAGES.md — the owner's map of every page (owner request, 2026-10-05).

The owner asked: "Please show me where i can view all pages." This writes that
list from the delivered tree, so it cannot go stale by hand. It names
START_PREVIEW.bat as the way to open the site, because a localhost URL is a
dead link from the machine the build runs on (see docs/RUN.md).

Run: python3 scripts/gen_page_index.py
"""
from __future__ import annotations

import glob
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

PERSONAL_PAGES = ("sports.html", "good_hubby.html")

PORTFOLIO = ("index.html", "about.html", "skills.html", "projects.html",
             "evidence.html", "contact.html", "cv.html", "experience.html",
             "thesis-demo.html")
ACADEMIC_PREFIX = ("Algorithms,", "Analysing", "Applied statistical",
                   "Data Management", "Deciphering", "Essential mathematics",
                   "Interactive design", "Introduction to computers",
                   "Introduction to statistics", "Machine Learning",
                   "Mathematical methods", "Numerical Analysis",
                   "Practical modern statistics", "Research Methods",
                   "The Data Professional", "Visualising Data",
                   "Honours.html", "Masters.html")


def bucket(page: str) -> str:
    if page in PORTFOLIO:
        return "Portfolio"
    if page.startswith(ACADEMIC_PREFIX):
        return "Academic coursework"
    if page == "404.html":
        return "Utility"
    return "Other"


def main() -> None:
    pages = [p for p in sorted(glob.glob("*.html")) if p != "footer.html"]
    personal = [p for p in pages if p in PERSONAL_PAGES]
    delivered = [p for p in pages if p not in PERSONAL_PAGES]

    groups: dict[str, list[str]] = {}
    for p in delivered:
        groups.setdefault(bucket(p), []).append(p)

    out = [
        "# Every page in the portfolio",
        "",
        "Generated by `scripts/gen_page_index.py` — do not hand-edit.",
        "",
        "## How to open the site",
        "",
        "1. Double-click **`START_PREVIEW.bat`** in this folder.",
        "2. Your browser opens the home page; every page below is reached by",
        "   adding its file name to the address.",
        "",
        "Nothing is live on the internet yet — nothing has been pushed, so",
        "these pages are only viewable through that launcher.",
        "",
    ]
    for name in ("Portfolio", "Academic coursework", "Utility", "Other"):
        if name not in groups:
            continue
        out += [f"## {name}", ""]
        out += [f"- `{p}`" for p in groups[name]]
        out.append("")

    out += [
        "## Unlisted personal pages",
        "",
        "These sit at the root like `Cute.html` and `2026.html`, but they are",
        "not part of the professional portfolio and nothing links to them.",
        "",
        "They are **unlisted, not private**: the files are served from a public",
        "repository, so anyone with the address can read them. `robots.txt`",
        "disallows them and they carry `noindex, nofollow`, which only keeps",
        "them out of search results.",
        "",
    ]
    out += [f"- `{p}`" for p in personal]
    out += ["", f"Total delivered pages: **{len(delivered)}** "
                f"(plus {len(personal)} unlisted personal pages).", ""]

    with open("PAGES.md", "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"wrote PAGES.md — {len(delivered)} delivered + {len(personal)} personal")


if __name__ == "__main__":
    main()
